"""allow <img> tags in mararkdown conversion

Revision ID: 32889266e9aa
Revises: b23761d2d8a
Create Date: 2014-08-03 17:45:36.451640

"""

# revision identifiers, used by Alembic.
revision = '32889266e9aa'
down_revision = 'b23761d2d8a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
