"""trying out replies

Revision ID: 408282c830d1
Revises: 4842581a5f23
Create Date: 2014-08-03 06:28:36.611668

"""

# revision identifiers, used by Alembic.
revision = '408282c830d1'
down_revision = '4842581a5f23'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('reply_to_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'reply_to_id')
    ### end Alembic commands ###
