"""changed default score

Revision ID: 4842581a5f23
Revises: 50af7af629b3
Create Date: 2014-08-03 03:05:46.791295

"""

# revision identifiers, used by Alembic.
revision = '4842581a5f23'
down_revision = '50af7af629b3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
