"""initial migration

Revision ID: 588622ed8086
Revises: None
Create Date: 2014-07-20 01:51:02.039633

"""

# revision identifiers, used by Alembic.
revision = '588622ed8086'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
