"""initial migration

Revision ID: a3369f8e329
Revises: None
Create Date: 2014-07-16 20:59:20.505003

"""

# revision identifiers, used by Alembic.
revision = 'a3369f8e329'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
