"""setting a default order_by

Revision ID: b23761d2d8a
Revises: 408282c830d1
Create Date: 2014-08-03 07:16:08.832343

"""

# revision identifiers, used by Alembic.
revision = 'b23761d2d8a'
down_revision = '408282c830d1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
